general.import = ["themes/theme.toml"]

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8
